server.port=8083
spring.application.name=inventory-service
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.prometheus.enabled=true
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
