apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-services
  namespace: demo
  labels:
    scenario: demo-services
spec:
  selector:
    matchLabels:
      scenario: demo-services
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
